package in.terek.photoapp.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import in.terek.photoapp.db.ImageFiles;

import in.terek.photoapp.db.ImageFilesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imageFilesDaoConfig;

    private final ImageFilesDao imageFilesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imageFilesDaoConfig = daoConfigMap.get(ImageFilesDao.class).clone();
        imageFilesDaoConfig.initIdentityScope(type);

        imageFilesDao = new ImageFilesDao(imageFilesDaoConfig, this);

        registerDao(ImageFiles.class, imageFilesDao);
    }
    
    public void clear() {
        imageFilesDaoConfig.clearIdentityScope();
    }

    public ImageFilesDao getImageFilesDao() {
        return imageFilesDao;
    }

}
